name: Bug Report
description: File a bug report
title: "[Bug]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve this project! Please read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide carefully before continuing.

  - type: checkboxes
    id: latest
    attributes:
      label: "I've read the documentation"
      options:
        - label: I'm running the latest version of tubearchivist-jf-plugin.
          required: true
        - label: I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.
          required: true
        - label: I have searched for both closed and open already existing issues about the problem I am reporting.
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: On what operating system are you running Tube Archivist on?
      placeholder: eg. Linux, Windows, ...
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Your Bug Report
      value: "## Describe the bug\n\n## Steps To Reproduce\n\n## Expected behavior"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Jellyfin log output
      description: Please copy and paste any relevant Jellyfin logs. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
